# Negative control: permanent external exchange flood (high I/O/demand)
profile_id: 0
dt: 0.01
window_sec: 0.2
method: linear
p_lag: 3
n_boot: 16
Mmin_db: 3.0
epsilon: 0.15
tau_max: 60.0
baseline_sec: 8.0
# Scenario to run with CLI:
#   python -m ldtc.cli.main omega-ingress-flood --config configs/negative_permanent_ex_flood.yml --mult 5 --duration 6
# Reproducible seeds
seed: 11
