# Negative control: risky external command when M below margin or low SoC
profile_id: 0
dt: 0.01
window_sec: 0.2
method: linear
p_lag: 3
n_boot: 16
Mmin_db: 3.0
epsilon: 0.15
tau_max: 60.0
# Run:
#   python -m ldtc.cli.main omega-command-conflict --config configs/negative_command_conflict.yml --observe 2
# Reproducible seeds
seed: 17
