# Negative control: SoC (E) rising without harvest logs (exogenous subsidy)
profile_id: 0
dt: 0.01
window_sec: 0.2
method: linear
p_lag: 3
n_boot: 16
Mmin_db: 3.0
epsilon: 0.15
tau_max: 60.0
baseline_sec: 6.0
# Run:
#   python -m ldtc.cli.main omega-exogenous-subsidy --config configs/profile_negative_exogenous_soc.yml --delta 0.2 --zero-harvest --duration 3
# Reproducible seeds
seed: 13


